//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detail
    {
        public int id_user { get; set; }
        public int id_project { get; set; }
        public Nullable<System.DateTime> join_date { get; set; }
        public Nullable<System.DateTime> leave_date { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual User User { get; set; }
    }
}
