//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManage.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class DevelopGroup
    {
        public DevelopGroup()
        {
            this.Users = new HashSet<User>();
        }
        [Display(Name = "ID Develop Group")]  //Thuộc tính Display để đặt lại tên cho cột
        [Required(ErrorMessage = "{0} must not be empty! ")]  //Kiểm tra rỗng
        public int id_develop_group { get; set; }

        [Display(Name = "Group Name")]   //Thuộc tính Display để đặt lại tên cho cột
        [Required(ErrorMessage = "{0} must not be empty! ")]  //Kiểm tra rỗng
        public string name_group { get; set; }

        [Display(Name = "Description")]   //Thuộc tính Display để đặt lại tên cho cột
        [Required(ErrorMessage = "{0} must not be empty! ")]  //Kiểm tra rỗng
        public string description { get; set; }

        [Display(Name = "Authorize")]   //Thuộc tính Display để đặt lại tên cho cột
        [Required(ErrorMessage = "{0} must not be empty! ")]  //Kiểm tra rỗng
        public int authorize { get; set; }

    
        public virtual ICollection<User> Users { get; set; }
    }
}
