//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManage.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Phase
    {
        public Phase()
        {
            this.Tasks = new HashSet<Task>();
        }

        public int id_phase { get; set; }

        [Display(Name = "Phase Name")]  //Thuộc tính Display để đặt lại tên cho cột
        [Required(ErrorMessage = "{0} must not be empty! ")]  //Kiểm tra rỗng
        public string phase_name { get; set; }

        [Display(Name = "Description")]  //Thuộc tính Display để đặt lại tên cho cột
        [Required(ErrorMessage = "{0} must not be empty! ")]  //Kiểm tra rỗng
        public string description { get; set; }

        [Display(Name = "Project")]  //Thuộc tính Display để đặt lại tên cho cột
        [Required(ErrorMessage = "{0} must not be empty! ")]  //Kiểm tra rỗng
        public int id_project { get; set; }

        [Display(Name = "Start Date")]  //Thuộc tính Display để đặt lại tên cho cột
        [Required(ErrorMessage = "{0} must not be empty! ")]  //Kiểm tra rỗng
        public System.DateTime start_date { get; set; }

        [Display(Name = "End Date")]  //Thuộc tính Display để đặt lại tên cho cột
        [Required(ErrorMessage = "{0} must not be empty! ")]  //Kiểm tra rỗng
        public System.DateTime end_date { get; set; }

        public int status { get; set; }
    
        public virtual ICollection<Task> Tasks { get; set; }
    }
}
