//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusType
    {
        public StatusType()
        {
            this.Tasks = new HashSet<Task>();
        }
    
        public int id_status_type { get; set; }
        public string name_status_type { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<Task> Tasks { get; set; }
    }
}
