//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskType
    {
        public int id_task_type { get; set; }
        public string name_task_type { get; set; }
        public string description { get; set; }
    }
}
