//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public Task()
        {
            this.Timesheets = new HashSet<Timesheet>();
        }
    
        public int id_task { get; set; }
        public string task_name { get; set; }
        public string summary_task { get; set; }
        public int id_project { get; set; }
        public int id_phase { get; set; }
        public System.DateTime plan_start_date { get; set; }
        public System.DateTime plan_end_date { get; set; }
        public int estimate_time { get; set; }
        public System.DateTime real_start_date { get; set; }
        public System.DateTime real_end_date { get; set; }
        public string description { get; set; }
        public string task_type { get; set; }
        public string status_task { get; set; }
        public string link { get; set; }
        public int reporter { get; set; }
        public string priority { get; set; }
    
        public virtual Phase Phase { get; set; }
        public virtual Project Project { get; set; }
        public virtual ICollection<Timesheet> Timesheets { get; set; }
    }
}
