//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManage.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Task
    {
        public Task()
        {
            this.Results = new HashSet<Result>();
            this.Timesheets = new HashSet<Timesheet>();
        }

        public int id_task { get; set; }

        [Display(Name = "Task Name")]  //Thuộc tính Display để đặt lại tên cho cột
        [Required(ErrorMessage = "{0} must not be empty! ")]  //Kiểm tra rỗng
        public string task_name { get; set; }

        [Display(Name = "Summary Task")]  //Thuộc tính Display để đặt lại tên cho cột
        [Required(ErrorMessage = "{0} must not be empty! ")]  //Kiểm tra rỗng
        public string summary_task { get; set; }

        [Display(Name = "Sprint")]  //Thuộc tính Display để đặt lại tên cho cột
        [Required(ErrorMessage = "{0} must not be empty! ")]  //Kiểm tra rỗng
        public int id_sprint { get; set; }

        [Display(Name = "Plan Start Date")]  //Thuộc tính Display để đặt lại tên cho cột
        [Required(ErrorMessage = "{0} must not be empty! ")]  //Kiểm tra rỗng
        public System.DateTime plan_start_date { get; set; }

        [Display(Name = "Plan End Date")]  //Thuộc tính Display để đặt lại tên cho cột
        [Required(ErrorMessage = "{0} must not be empty! ")]  //Kiểm tra rỗng
        public System.DateTime plan_end_date { get; set; }

        [Display(Name = "Estimate Time")]  //Thuộc tính Display để đặt lại tên cho cột
        [Required(ErrorMessage = "{0} must not be empty! ")]  //Kiểm tra rỗng
        public int estimate_time { get; set; }
        public System.DateTime real_start_date { get; set; }
        public System.DateTime real_end_date { get; set; }

        [Display(Name = "Description")]  //Thuộc tính Display để đặt lại tên cho cột
        [Required(ErrorMessage = "{0} must not be empty! ")]  //Kiểm tra rỗng
        public string description { get; set; }

        [Display(Name = "Type")]  //Thuộc tính Display để đặt lại tên cho cột
        [Required(ErrorMessage = "{0} must not be empty! ")]  //Kiểm tra rỗng
        public int type { get; set; }
        public int status { get; set; }
        public string link { get; set; }
        public int reporter { get; set; }

        [Display(Name = "Priority")]  //Thuộc tính Display để đặt lại tên cho cột
        [Required(ErrorMessage = "{0} must not be empty! ")]  //Kiểm tra rỗng
        public int priority { get; set; }

        [Display(Name = "Assignee")]  //Thuộc tính Display để đặt lại tên cho cột
        [Required(ErrorMessage = "{0} must not be empty! ")]  //Kiểm tra rỗng
        public int assignee_to { get; set; }
    
        public virtual Phase Phase { get; set; }
        public virtual ICollection<Result> Results { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Timesheet> Timesheets { get; set; }
    }
}
