//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timesheet
    {
        public int id_task { get; set; }
        public int id_user { get; set; }
        public int time { get; set; }
        public string description { get; set; }
        public int type_of_work { get; set; }
    
        public virtual Task Task { get; set; }
        public virtual User User { get; set; }
    }
}
