//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeOfWork
    {
        public TypeOfWork()
        {
            this.Timesheets = new HashSet<Timesheet>();
        }
    
        public int id_work_type { get; set; }
        public string name_work_type { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<Timesheet> Timesheets { get; set; }
    }
}
