//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Details = new HashSet<Detail>();
            this.Projects = new HashSet<Project>();
            this.Tasks = new HashSet<Task>();
            this.Timesheets = new HashSet<Timesheet>();
        }
    
        public int id_user { get; set; }
        public string account { get; set; }
        public string password { get; set; }
        public string user_name { get; set; }
        public int id_develop_group { get; set; }
        public string mail { get; set; }
        public string status { get; set; }
        public int authorize { get; set; }
        public string position { get; set; }
    
        public virtual ICollection<Detail> Details { get; set; }
        public virtual DevelopGroup DevelopGroup { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
        public virtual ICollection<Timesheet> Timesheets { get; set; }
    }
}
