//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManage.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class User
    {
        public User()
        {
            this.Details = new HashSet<Detail>();
            this.Projects = new HashSet<Project>();
            this.Tasks = new HashSet<Task>();
            this.Timesheets = new HashSet<Timesheet>();
        }

        [Display(Name = "ID User")]  //Thuộc tính Display để đặt lại tên cho cột
        [Required(ErrorMessage = "{0} must not be empty! ")]  //Kiểm tra rỗng
        public int id_user { get; set; }

        [Display(Name = "Account")]  //Thuộc tính Display để đặt lại tên cho cột
        [Required(ErrorMessage = "{0} must not be empty! ")]  //Kiểm tra rỗng
        public string account { get; set; }

        [Display(Name = "Password")]  //Thuộc tính Display để đặt lại tên cho cột
        [Required(ErrorMessage = "{0} must not be empty! ")]  //Kiểm tra rỗng
        public string password { get; set; }

        [Display(Name = "User Name")]  //Thuộc tính Display để đặt lại tên cho cột
        [Required(ErrorMessage = "{0} must not be empty! ")]  //Kiểm tra rỗng
        public string user_name { get; set; }

        [Display(Name = "Develop Group")]  //Thuộc tính Display để đặt lại tên cho cột
        [Required(ErrorMessage = "{0} must not be empty! ")]  //Kiểm tra rỗng
        public int id_develop_group { get; set; }

        [Display(Name = "Email")]  //Thuộc tính Display để đặt lại tên cho cột
        [Required(ErrorMessage = "{0} must not be empty! ")]  //Kiểm tra rỗng
        public string mail { get; set; }

        [Display(Name = "Status")]  //Thuộc tính Display để đặt lại tên cho cột
        [Required(ErrorMessage = "{0} must not be empty! ")]  //Kiểm tra rỗng
        public string status { get; set; }

        [Display(Name = "Authorize")]  //Thuộc tính Display để đặt lại tên cho cột
        [Required(ErrorMessage = "{0} must not be empty! ")]  //Kiểm tra rỗng
        public int authorize { get; set; }

        [Display(Name = "Possition")]  //Thuộc tính Display để đặt lại tên cho cột
        [Required(ErrorMessage = "{0} must not be empty! ")]  //Kiểm tra rỗng
        public string position { get; set; }
    
        public virtual ICollection<Detail> Details { get; set; }
        public virtual DevelopGroup DevelopGroup { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
        public virtual ICollection<Timesheet> Timesheets { get; set; }
    }
}
