//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Tasks = new HashSet<Task>();
            this.Tasks1 = new HashSet<Task>();
        }
    
        public int id_user { get; set; }
        public string account { get; set; }
        public string password { get; set; }
        public string user_name { get; set; }
        public int id_develop_group { get; set; }
        public int id_authority { get; set; }
        public string mail { get; set; }
        public string id_status_user { get; set; }
    
        public virtual AuthorityType AuthorityType { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
        public virtual ICollection<Task> Tasks1 { get; set; }
    }
}
